name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  ci:
    name: "CI ${{ matrix.python-version }} (conda: ${{ matrix.conda }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conda: [true, false]
        python-version: ["3.11"]
    defaults:
      run:
        # https://github.com/conda-incubator/setup-miniconda#use-a-default-shell
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      if: ${{ matrix.conda == true }}
      with:
        activate-environment: scitt
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Run tests with conda
      if: ${{ matrix.conda == true }}
      run: |
        python -m pip install -e .
        python -m pytest
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.conda == false }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests with venv
      if: ${{ matrix.conda == false }}
      run: ./run-tests.sh

  ci-cd-build-and-push-image-container:
    name: CI/CD (container)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      CONTAINER_IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
